In [39]:
pip install ipynb >> None

Note: you may need to restart the kernel to use updated packages.

In [1]:
import import_ipynb

import numpy as np
import pandas as pd
import featuretools as ft
from featuretools import selection


from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest, SelectPercentile
from sklearn.feature_selection import chi2, mutual_info_classif

c:\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
data = pd.read_csv('data_raw.csv')
data = data.drop(['Date.1', 'Date.2', 'Date.3'], axis=1)
data.shape

(7545, 513)

In [3]:
data.head()

,Date,^GSPC_Open,^GSPC_High,^GSPC_Low,^GSPC_Close,^GSPC_Adj Close,^GSPC_Volume,^GSPC_EMA_5,^GSPC_EMA_10,^GSPC_EMA_20,...,DX-Y.NYB Last Close 1,DX-Y.NYB Last Close 2,DX-Y.NYB Last Close 3,DX-Y.NYB Last Close 4,DX-Y.NYB Last Close 5,DX-Y.NYB Last Close 6,DX-Y.NYB Last Close 7,DX-Y.NYB Last Close 8,DX-Y.NYB Last Close 9,DX-Y.NYB Last Close 10
0,1993-01-29,438.670013,438.929993,436.910004,438.779999,438.779999,247200000,438.395204,437.498333,436.381358,...,91.279999,91.360001,90.550003,90.470001,91.410004,92.250000,91.550003,92.000000,92.059998,93.040001
1,1993-02-01,438.779999,442.519989,438.779999,442.519989,442.519989,238570000,439.770132,438.411362,436.965990,...,92.459999,91.279999,91.360001,90.550003,90.470001,91.410004,92.250000,91.550003,92.000000,92.059998
2,1993-02-02,442.519989,442.869995,440.760010,442.549988,442.549988,271560000,440.696751,439.163839,437.497799,...,93.559998,92.459999,91.279999,91.360001,90.550003,90.470001,91.410004,92.250000,91.550003,92.000000
3,1993-02-03,442.559998,447.350006,442.559998,447.200012,447.200012,345410000,442.864504,440.624961,438.421819,...,93.919998,93.559998,92.459999,91.279999,91.360001,90.550003,90.470001,91.410004,92.250000,91.550003
4,1993-02-04,447.200012,449.859985,447.200012,449.559998,449.559998,351140000,445.096336,442.249513,439.482598,...,94.239998,93.919998,93.559998,92.459999,91.279999,91.360001,90.550003,90.470001,91.410004,92.250000

In [4]:
#remove_low_information_features(feature_matrix)
#remove_highly_correlated_features(feature_matrix)
#remove_highly_null_features(feature_matrix)
#remove_single_value_features(feature_matrix)
filtered = selection.remove_highly_correlated_features(data, pct_corr_threshold=0.98)
filtered = selection.remove_low_information_features(filtered)
filtered = selection.remove_highly_null_features(filtered)
filtered = selection.remove_single_value_features(filtered)
tickers = ['^VIX', '^IXIC', 'DX-Y.NYB', '^GSPC']
filtered['^GSPC_High'] = data['^GSPC_High']
filtered['^GSPC_Low'] = data['^GSPC_Low']
filtered['^GSPC_Close'] = data['^GSPC_Close']
filtered['^VIX_Close'] = data['^VIX_Close']
filtered['^IXIC_Close'] = data['^IXIC_Close']
filtered['^DX-Y.NYB_Close'] = data['^DX-Y.NYB_Close']
filtered = filtered.dropna()
filtered.head()

,Date,^GSPC_Open,^GSPC_Volume,^GSPC_SQZ_20_2.0_20_1.5,^GSPC_SQZ_ON,^GSPC_ABER_ATR_5_15,^GSPC_ADOSC_3_10,^GSPC_ADX_14,^GSPC_DMP_14,^GSPC_DMN_14,...,DX-Y.NYB_VHF_28,DX-Y.NYB level 5,DX-Y.NYB level 10,DX-Y.NYB level 20,DX-Y.NYB level 25,DX-Y.NYB level 30,DX-Y.NYB level 50,^GSPC_High,^GSPC_Low,^GSPC_Close
0,1993-01-29,438.670013,247200000,7.049998,False,2.902007,6.886895e+07,18.006061,28.075804,22.869827,...,0.244481,1.0,1.0,0.0,0.0,1.0,0.0,438.929993,436.910004,438.779999
1,1993-02-01,438.779999,238570000,7.881663,False,2.957872,1.703827e+08,18.460351,34.209112,20.804444,...,0.237145,0.0,0.0,0.0,0.0,0.0,0.0,442.519989,438.779999,442.519989
2,1993-02-02,442.519989,271560000,7.234996,False,2.901346,2.566182e+08,18.970118,33.292546,19.722291,...,0.260181,0.0,0.0,0.0,0.0,0.0,0.0,442.869995,440.760010,442.549988
3,1993-02-03,442.559998,345410000,7.144994,False,3.027924,3.715875e+08,20.417289,40.078885,17.493099,...,0.278434,1.0,0.0,0.0,0.0,0.0,0.0,447.350006,442.559998,447.200012
4,1993-02-04,447.200012,351140000,8.356664,False,3.003394,4.713655e+08,22.193214,43.509068,16.387681,...,0.316940,1.0,0.0,0.0,0.0,0.0,0.0,449.859985,447.200012,449.559998

In [5]:
filtered.shape, data.shape

((7534, 242), (7545, 513))

In [7]:
filtered.to_csv('filtered_features.csv')